### PR TITLE
Show lines of code per package path

### PR DESCRIPTION
**Pull request by alok87**
Solves https://github.com/google/godepq/issues/30

* Lines of code per package and in total

```bash
$ go run godepq.go  -from .
Packages:
github.com/google/godepq (203)
github.com/google/godepq/deps (560)

Total Lines Of Code: 763
````

### CODE REVIEW

**Comment by alok87** [comment]
Please help with the CI it does not looks related to this change.

**Comment by tallclair** [comment]
Thanks for the PR. The gocloc package is interesting, with the ability to separate out comments & blank lines, but it looks like it's missing the ability to exclude tests.

I had actually started work on similar functionality - you can find my WIP commit here: https://github.com/tallclair/godepq/commit/dae20136b1620b82dc0acf5f77f1647a24ef0b4c

What do you think about merging these 2 efforts? Maybe use the naive code counting for now, with your CLI changes?

Also, the CI errors are from a dependency you're pulling in. If we stick with the gocloc library, I'd like to vendor it.

**Comment by alok87** [comment]
Merged  👍 
Opened an issue in gocloc to add support to ignore file paths https://github.com/hhatto/gocloc/issues/15

**Comment by tallclair** [comment]
Thanks, changes look good, but I liked that you put the loc output behind a flag before - would you mind adding the flag back?

**Comment by alok87** [comment]
@tallclair sure, but there are 2 print functions. 
`func printDot()` and `func printList()`, should i put loc output behind the flag for both of them?

**Comment by tallclair** [comment]
> should i put loc output behind the flag for both of them?

Yes please!

**Comment by alok87** [comment]
@tallclair done

**Comment by tallclair** [comment]
lgtm

**Pull request merged**
